### ISSUE TITLE
Current build does not build 

### ISSUE THREAD

**Issue by CrazyLemon** [Sioro-Neoku/go-peerflix#18]
So i kinda forgot to sync my local repo for a long time now. And now that i did i can't seem to build go-peerflix.
The error is 
./fileEntry.go:29: f.Torrent undefined (type *torrent.File has no field or method Torrent)

What did i do wrong?

Before syncing i could easily build.

**Comment by Sioro-Neoku** [comment]
You should probably update the other libraries as well:
 `go get -u "github.com/anacrolix/torrent/"`

**Comment by CrazyLemon** [comment]
That did it. Thanks.
