### ISSUE TITLE
What is it?

### ISSUE THREAD

**Issue by Infy06** [Sioro-Neoku/go-peerflix#35]
Okay i want o know before trying it out 
1) can we DIRECT DOWNLOAD  unlimited torrents with this?
2) is it like Jpillora Cloud torrent in the sense can we download any type of torrent files (games,software,movies etc..)
3) is the download speed varied on seeds or it just simply download it?
sorry for being a noob i have been trying to find a good alternative to Jpillora cloud torrent and i came up with this please answer my question
~Thank You

**Comment by hako** [comment]
@Infy06 go-peerflix is a Go port of [peerflix](https://github.com/mafintosh/peerflix)

1) I'm pretty sure you can download unlimited torrents with this.
2) This can only download & play torrent files **which are video and audio files**.
3) Download speed does vary on seeds.

**Comment by Sioro-Neoku** [comment]
@hako's answers are correct.
Thank you for answering!
