### ISSUE TITLE
error  building src/golang.org/x/net/context/go19.go:15:14: expected type, found '='

### ISSUE THREAD

**Issue by Deluxo** [Sioro-Neoku/go-peerflix#38]
error when building:

src/golang.org/x/net/context/go19.go:15:14: expected type, found '='
src/golang.org/x/net/context/go19.go:20:17: expected type, found '='
exit status 2

**Comment by nochso** [comment]
Which version of Go are you using? What commands did you run to get the packages and build it?

**Comment by Deluxo** [comment]
The problem appears to be in the aur pkg, not this repo's source code.
Until I find a better way to build that package, I have no other problems.

go ver. 1.8.3 linux 64b
