### ISSUE TITLE
[enhancement] Always prioritize/force next 5%

### ISSUE THREAD

**Issue by fcarreiro** [Sioro-Neoku/go-peerflix#39]
Hi! According to what I could see in the code and experience while using the program, it seems that once the first 5% is downloaded, then the rest of the torrent could be downloaded in any order. This can result in the playback freezing after the first 5% is played.

I propose that, after each 5% is downloaded, the next 5% is prioritized, in order. Also, the number could be made smaller but that's more of an implementation detail. If you agree, I could try to make this work and submit a pull request.

As a side topic, I think it would also be nice if seeding is enabled by default.

Let me know what you think!
Cheers

PS: I'll leave the question of whether to prioritize or only download each 5% for later.

**Comment by Sioro-Neoku** [comment]
Hey,

We prioritize the next 1% at the moment automatically: https://github.com/Sioro-Neoku/go-peerflix/blob/0fb5bffffebc492d60fd4d3bcb001db9989f1c70/fileEntry.go#L31-L32

Although seeding is nice, I will not make it a default, as it:

- Might slow down downloads
- Might cause legal trouble for some people
