### ISSUE TITLE
Unable to build on Linux

### ISSUE THREAD

**Issue by milankragujevic** [Sioro-Neoku/go-peerflix#4]
I am unable to build and install go-peerflix on arm v7 hardfloat. I get the following error. I'm using Scaleway if it helps.
    go get github.com/Sioro-Neoku/go-peerflix
    # github.com/anacrolix/torrent/dht
    /root/go/src/github.com/anacrolix/torrent/dht/addr.go:6: import /root/go/pkg/linux_arm/github.com/anacrolix/missinggo.a: object is [linux arm go1.2.1 X:none] expected [linux arm go1.4.2 X:precisestack]
    # github.com/anacrolix/utp
    /root/go/src/github.com/anacrolix/utp/utp.go:29: import /root/go/pkg/linux_arm/github.com/anacrolix/jitter.a: object is [linux arm go1.2.1 X:none] expected [linux arm go1.4.2 X:precisestack]

**Comment by Sioro-Neoku** [comment]
Seems like the error is originating from https://github.com/anacrolix/torrent .
I opened the ticket to coordinate about the fixes.

**Comment by milankragujevic** [comment]
It's now fixed. If anyone's got a similar problem, just run 

> rm -r "$GOPATH/pkg"
