### ISSUE TITLE
Use Go modules

### ISSUE THREAD

**Issue by anacrolix** [Sioro-Neoku/go-peerflix#45]
It might be worth incorporating Go modules into this repo now. In particular, some API changes that caused issues in the past with anacrolix/torrent could be avoided. It's worth noting however, that in the absence of a go.mod in this repo, v1 of anacrolix/torrent will be selected indefinitely into the future, which shouldn't break API (too much).

**Comment by Sioro-Neoku** [comment]
Makes sense.

Thanks =)
