### ISSUE TITLE
Add proxy support

### ISSUE THREAD

**Issue by MilesDust** [Sioro-Neoku/go-peerflix#53]
I would like to be able to set a proxy for go-peerflix to connect with peers through. A commandline flag to specify it would be good, e.g. `go-peerflix --proxy=https://[username:password@]127.0.0.1:8080`.

**Comment by Sioro-Neoku** [comment]
You can already configure a proxy address using
```bash
export HTTP_PROXY="https://[username:password@]127.0.0.1:8080"
```
